import { Router } from 'express'; import { ObjectId } from 'mongodb'; import { database } from '../db/mongo.js'; import { authenticate, csrf } from '../middleware/auth.js'; import type { Resume } from '../types/domain.js'; import { resumePatchSchema, resumeSchema } from '../validators/schemas.js'; import { asyncRoute, fail, getValidated, ok, validate } from '../utils/http.js';
const router=Router(); router.use(authenticate); const id=(v:string|string[])=>typeof v==='string'&&ObjectId.isValid(v)?new ObjectId(v):undefined;
router.get('/',asyncRoute(async(req,res)=>{const resumes=await (await database()).collection<Resume>('resumes').find({userId:req.auth!.user._id},{projection:{content:0}}).sort({updatedAt:-1}).toArray();return ok(res,{resumes});}));
router.post('/',csrf,validate(resumeSchema),asyncRoute(async(req,res)=>{const input=getValidated<typeof resumeSchema._output>(req),now=new Date();const doc:Resume={userId:req.auth!.user._id,...input,paymentState:'unpaid',downloadCount:0,createdAt:now,updatedAt:now};const result=await (await database()).collection<Resume>('resumes').insertOne(doc);return ok(res,{resume:{...doc,_id:result.insertedId}},201);}));
router.get('/:id',asyncRoute(async(req,res)=>{const resumeId=id(req.params.id);if(!resumeId)return fail(res,404,'NOT_FOUND','Resume not found');const resume=await (await database()).collection<Resume>('resumes').findOne({_id:resumeId,userId:req.auth!.user._id});return resume?ok(res,{resume}):fail(res,404,'NOT_FOUND','Resume not found');}));
router.patch('/:id',csrf,validate(resumePatchSchema),asyncRoute(async(req,res)=>{const resumeId=id(req.params.id);if(!resumeId)return fail(res,404,'NOT_FOUND','Resume not found');const patch=getValidated<typeof resumePatchSchema._output>(req),db=await database(), current=await db.collection<Resume>('resumes').findOne({_id:resumeId,userId:req.auth!.user._id});if(!current)return fail(res,404,'NOT_FOUND','Resume not found');await db.collection('resumeVersions').insertOne({resumeId,userId:req.auth!.user._id,version:Date.now(),content:current.content,createdAt:new Date()});await db.collection<Resume>('resumes').updateOne({_id:resumeId,userId:req.auth!.user._id},{$set:{...patch,updatedAt:new Date()}});const resume=await db.collection<Resume>('resumes').findOne({_id:resumeId,userId:req.auth!.user._id});return ok(res,{resume});}));
router.post('/:id/duplicate',csrf,asyncRoute(async(req,res)=>{const resumeId=id(req.params.id);if(!resumeId)return fail(res,404,'NOT_FOUND','Resume not found');const db=await database(),source=await db.collection<Resume>('resumes').findOne({_id:resumeId,userId:req.auth!.user._id});if(!source)return fail(res,404,'NOT_FOUND','Resume not found');const {_id,...copy}=source,now=new Date();const result=await db.collection<Resume>('resumes').insertOne({...copy,title:`${source.title} (copy)`,paymentState:'unpaid',downloadCount:0,createdAt:now,updatedAt:now});return ok(res,{resume:{...copy,_id:result.insertedId}},201);}));
router.delete('/:id',csrf,asyncRoute(async(req,res)=>{const resumeId=id(req.params.id);if(!resumeId)return fail(res,404,'NOT_FOUND','Resume not found');const result=await (await database()).collection<Resume>('resumes').deleteOne({_id:resumeId,userId:req.auth!.user._id});return result.deletedCount?res.status(204).end():fail(res,404,'NOT_FOUND','Resume not found');}));
export default router;
