import crypto from 'node:crypto';
import type { NextFunction, Request, Response } from 'express';
import { ObjectId } from 'mongodb';
import { env } from '../config/env.js'; import { database } from '../db/mongo.js'; import type { User } from '../types/domain.js'; import { fail } from '../utils/http.js';
declare global { namespace Express { interface Request { auth?: { user: User & {_id: ObjectId}; sessionId: ObjectId }; } } }
const hash = (value: string) => crypto.createHash('sha256').update(value).digest('hex');
export const randomSecret = () => crypto.randomBytes(32).toString('base64url');
export async function createSession(res: Response, userId: ObjectId) { const token=randomSecret(), csrf=randomSecret(), now=new Date(), expiresAt=new Date(now.getTime()+env.SESSION_TTL_DAYS*86400000); const db=await database(); await db.collection('sessions').insertOne({userId,tokenHash:hash(token),csrfHash:hash(csrf),createdAt:now,lastSeenAt:now,expiresAt}); const isProd=env.NODE_ENV==='production'; const options={httpOnly:true,secure:isProd,sameSite:(isProd?'none':'lax') as 'none'|'lax',path:'/',expires:expiresAt}; res.cookie('sid',token,options); res.cookie('csrf',csrf,{...options,httpOnly:false,sameSite:(isProd?'none':'lax') as 'none'|'lax'}); }
export const authenticate = async (req: Request,res: Response,next: NextFunction) => { const token=req.cookies?.sid; if(!token) return fail(res,401,'UNAUTHENTICATED','Authentication required'); const db=await database(); const session=await db.collection('sessions').findOne({tokenHash:hash(token),expiresAt:{$gt:new Date()}}); if(!session) return fail(res,401,'UNAUTHENTICATED','Session expired'); const user=await db.collection<User>('users').findOne({_id:session.userId}); if(!user) return fail(res,401,'UNAUTHENTICATED','Account unavailable'); req.auth={user,sessionId:session._id}; void db.collection('sessions').updateOne({_id:session._id},{$set:{lastSeenAt:new Date()}}); next(); };
export const csrf = async (req: Request,res: Response,next: NextFunction) => { if(['GET','HEAD','OPTIONS'].includes(req.method)) return next(); const token=req.cookies?.csrf, provided=req.get('x-csrf-token'); if(!token||!provided||token!==provided) return fail(res,403,'CSRF_INVALID','Invalid request token'); const db=await database(); const session=await db.collection('sessions').findOne({_id:req.auth?.sessionId,csrfHash:hash(token)}); if(!session) return fail(res,403,'CSRF_INVALID','Invalid request token'); next(); };
export const adminOnly = (req: Request,res: Response,next: NextFunction) => req.auth?.user.role==='admin' ? next() : fail(res,403,'FORBIDDEN','Administrator access required');
export const clearSession = async (req: Request,res: Response) => { if(req.auth) { const db=await database(); await db.collection('sessions').deleteOne({_id:req.auth.sessionId}); } const isProd=env.NODE_ENV==='production'; const clearOpts={path:'/',secure:isProd,sameSite:(isProd?'none':'lax') as 'none'|'lax'}; res.clearCookie('sid',clearOpts); res.clearCookie('csrf',clearOpts); };
